Microlevel changes
pyrsia/pyrsia.github.io pull request #16
Opened 2022-02-09 10:06 UTC by AbhijithGanesh

Fixes #15

Signed-off-by: Abhijith Ganesh <g.abhijith14122003@gmail.com>

2022-02-09 10:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pyrsia/pyrsia.github.io?pullRequest=16) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pyrsia/pyrsia.github.io?pullRequest=16) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pyrsia/pyrsia.github.io?pullRequest=16) it.</sub>

2022-02-09 13:22 UTC, mgrand commented on content/en/events/_index.md
> +<iframe src="https://calendar.google.com/calendar/u/0/embed?src=pyrsiaopensource@gmail.com" style="border: 0" width="600" height="450" frameborder="0" scrolling="no"></iframe>
If you want to make a change to make the picture better formatted for different screen sizes, then you will need to do something to allow the size of the image to be based on the size of the screen. Just setting size to a different fixed value changes which screens it looks good or bad on.

What is the addition of the /u/0 in the URL path for?

2022-02-09 13:42 UTC, AbhijithGanesh commented on content/en/events/_index.md
> +<iframe src="https://calendar.google.com/calendar/u/0/embed?src=pyrsiaopensource@gmail.com" style="border: 0" width="600" height="450" frameborder="0" scrolling="no"></iframe>
Apologies, the u/0  is a mistake , how do you think the width and height should be applies?

2022-02-09 13:48 UTC, mgrand commented on content/en/events/_index.md
> +<iframe src="https://calendar.google.com/calendar/u/0/embed?src=pyrsiaopensource@gmail.com" style="border: 0" width="600" height="450" frameborder="0" scrolling="no"></iframe>
I am not a UI expert. I understand that there are techniques using JavaScript or typeScript for determining the screen size and resizing screen elements appropriately. Try Googling for more details.

2022-02-09 16:11 UTC, AbhijithGanesh commented on content/en/events/_index.md
> +<iframe src="https://calendar.google.com/calendar/u/0/embed?src=pyrsiaopensource@gmail.com" style="border: 0" width="600" height="450" frameborder="0" scrolling="no"></iframe>
I am aware of resizing but this doesn't involve any css and I am not sure how to do this without css

2022-02-09 17:00 UTC, sbtaylor15 approved these changes
css can be used to resize the images based on the screen size by using a [media query](https://www.w3schools.com/css/css_rwd_mediaqueries.asp).

Approving these changes and we should create another issue for making the images responsive to screen size.  Also, there may be a Hugo shortcode or partial that does this as well.

2022-02-09 18:16 UTC, prince-chrismc reviewed
Great work!

This this trick... `iframe` props are CSS based so the regular stuff works here

2022-02-09 18:16 UTC, prince-chrismc commented on content/en/events/_index.md
> +<iframe src="https://calendar.google.com/calendar/u/0/embed?src=pyrsiaopensource@gmail.com" style="border: 0" width="600" height="450" frameborder="0" scrolling="no"></iframe>
This will make it always the right size

- width 100% with auto height (sometimes it's a little tall but it's always on screen)
- remove the extra width in the URL query (the browser can handle this just fine)

```suggestion
<img src="https://images.squarespace-cdn.com/content/v1/57125c2c2b8dde54a34b537f/1610505862182-EHP7C22V98L1980CR155/Pyrsia.jpg" alt="Pyrsia Square and Torches" width="100%">
```

2022-02-09 19:44 UTC, sbtaylor15 requested changes

2022-02-09 19:44 UTC, sbtaylor15 commented on content/en/events/_index.md
> +<img src="https://images.squarespace-cdn.com/content/v1/57125c2c2b8dde54a34b537f/1610505862182-EHP7C22V98L1980CR155/Pyrsia.jpg" alt="Pyrsia Square and Torches" width="100%">
This doesn't look correct.  The calendar was deleted and replaced by an image.  Need to keep the calendar.

2022-02-09 19:46 UTC, AbhijithGanesh commented on content/en/events/_index.md
> +<img src="https://images.squarespace-cdn.com/content/v1/57125c2c2b8dde54a34b537f/1610505862182-EHP7C22V98L1980CR155/Pyrsia.jpg" alt="Pyrsia Square and Torches" width="100%">
Instead of replacing the `iframe` I mistakenly committed Chris's suggestion and it was for an image

2022-02-09 19:48 UTC, AbhijithGanesh commented on content/en/events/_index.md
> +<img src="https://images.squarespace-cdn.com/content/v1/57125c2c2b8dde54a34b537f/1610505862182-EHP7C22V98L1980CR155/Pyrsia.jpg" alt="Pyrsia Square and Torches" width="100%">
Patched

2022-02-09 19:50 UTC, sbtaylor15 approved these changes
/lgtm

2022-02-10 00:12 UTC, prince-chrismc commented
Sorry for my bad suggestion... this is linked to the issue about the image dimensions https://github.com/pyrsia/pyrsia/issues/343
I did not notice the changes were unrelated.

Is there a reason the issue is linked?

2022-02-10 01:34 UTC, mgrand approved these changes

2022-02-10 04:39 UTC, AbhijithGanesh commented
The issue was transferred to the main repository and I think the link got broken because of that

2022-02-10 04:39 UTC, AbhijithGanesh commented
Closes #342

2022-02-10 22:11 UTC, prince-chrismc commented
> The issue was transferred to the main repository and I think the link got broken because of that

the link automatically gets updated 🤯

2022-02-10 22:12 UTC, merged