Release v0.2.3 page
pyrsia/pyrsia.github.io pull request #160
Opened 2023-01-13 21:20 UTC by dasmanas

Release page for v0.2.3

2023-01-13 22:26 UTC, fishseabowl approved these changes

2023-01-13 23:06 UTC, betarelease requested changes

2023-01-13 23:06 UTC, betarelease commented on blog/2023-01-13-pyrsia-0.2.3-released.md
> +- name: Manas Das
You can just say

`authors: manas_das`

since that is your entry in authors.yml

2023-01-13 23:06 UTC, betarelease commented on blog/2023-01-13-pyrsia-0.2.3-released.md
> +members. In this year we have appetite to solve few high stake issue in Software Supply Chain.
In this year we continue on our mission to solve few high stakes issues in Software Supply Chain.

2023-01-13 23:09 UTC, betarelease commented on blog/2023-01-13-pyrsia-0.2.3-released.md
> +* Improved release docs with manual test plan
I would say instead of just listing the release notes contextualize them for the user.  Try to explain why a change was made - like you can explain how fixing the brew installer listing helps the user.

2023-01-14 01:02 UTC, dasmanas commented on blog/2023-01-13-pyrsia-0.2.3-released.md
> +* Improved release docs with manual test plan
added more context.

2023-01-14 01:02 UTC, dasmanas commented on blog/2023-01-13-pyrsia-0.2.3-released.md
> +members. In this year we have appetite to solve few high stake issue in Software Supply Chain.
done

2023-01-14 01:02 UTC, dasmanas commented on blog/2023-01-13-pyrsia-0.2.3-released.md
> +- name: Manas Das
done

2023-01-14 19:30 UTC, sbtaylor15 approved these changes
/lgtm

2023-01-14 19:34 UTC, merged